version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]


  # Un-Comment when a dependencies manifest is added to the repository
  # - package-ecosystem: npm
  #   directory: /
  #   schedule:
  #     interval: weekly
  #   groups:
  #     dependencies:
  #       patterns: ["*"]

